# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calc.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncalc.proto\x12\x04\x63\x61lc\"!\n\x10OperationRequest\x12\r\n\x05value\x18\x01 \x01(\x01\" \n\x0eOperationReply\x12\x0e\n\x06result\x18\x01 \x01(\x01\"*\n\x12\x43\x61lculationRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"&\n\x10\x43\x61lculationReply\x12\x12\n\nhypotenuse\x18\x01 \x01(\x01\x32J\n\x10OperationService\x12\x36\n\x06Square\x12\x16.calc.OperationRequest\x1a\x14.calc.OperationReply2S\n\x12\x43\x61lculationService\x12=\n\tCalculate\x12\x18.calc.CalculationRequest\x1a\x16.calc.CalculationReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONREQUEST']._serialized_start=20
  _globals['_OPERATIONREQUEST']._serialized_end=53
  _globals['_OPERATIONREPLY']._serialized_start=55
  _globals['_OPERATIONREPLY']._serialized_end=87
  _globals['_CALCULATIONREQUEST']._serialized_start=89
  _globals['_CALCULATIONREQUEST']._serialized_end=131
  _globals['_CALCULATIONREPLY']._serialized_start=133
  _globals['_CALCULATIONREPLY']._serialized_end=171
  _globals['_OPERATIONSERVICE']._serialized_start=173
  _globals['_OPERATIONSERVICE']._serialized_end=247
  _globals['_CALCULATIONSERVICE']._serialized_start=249
  _globals['_CALCULATIONSERVICE']._serialized_end=332
# @@protoc_insertion_point(module_scope)
